export const AUTH_ACTION = {
  LOGIN: 'LOGIN',
  REQUEST: 'LOGIN_REQUEST',
  SUCCESS: 'LOGIN_SUCCESS',
  ERROR: 'LOGIN_ERROR',
};

export const PROFILE_ACTIONS = {
  GET_PROFILE: 'GET_PROFILE',
  GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  GET_PROFILE_ERROR: 'GET_PROFILE_ERROR',
  CLEAR_PROFILE: 'CLEAR_PROFILE',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  UPDATE_PROFILE_REQUEST: 'UPDATE_PROFILE_REQUEST',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_ERROR: 'UPDATE_PROFILE_ERROR',
};

export const CODES_ACTIONS = {
  GET_MY_CODES: 'GET_MY_CODES',
  GET_MY_CODES_REQUEST: 'GET_MY_CODES_REQUEST',
  GET_MY_CODES_SUCCESS: 'GET_MY_CODES_SUCCESS',
  GET_MY_CODES_ERROR: 'GET_MY_CODES_ERROR',
  CREATE_QR_CODE: 'CREATE_QR_CODE',
  CREATE_QR_CODE_REQUEST: 'CREATE_QR_CODE_REQUEST',
  CREATE_QR_CODE_SUCCESS: 'CREATE_QR_CODE_SUCCESS',
  CREATE_QR_CODE_ERROR: 'CREATE_QR_CODE_ERROR',
};
