export const AUTH_ACTION = {
  LOGIN: 'LOGIN',
  REQUEST: 'LOGIN_REQUEST',
  SUCCESS: 'LOGIN_SUCCESS',
  ERROR: 'LOGIN_ERROR',
};

export const PROFILE_ACTIONS = {
  GET_PROFILE: 'GET_PROFILE',
  GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  GET_PROFILE_ERROR: 'GET_PROFILE_ERROR',
};
